name: Publish Docker Image
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      appName:
        description: 'Name of the Application - for which CI is triggered'
        required: true
        type: string
      branch:
        description: 'Name of the branch - to checkout code. By default, checkout will be from main branch'
        required: false
        type: string
        default: 'master'

jobs:
  docker-push:
    name: Push Docker Image to Github Packages and update Dev Image Tag
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.appName }}
          #name: app
          path: /tmp
      - name: Push Docker image
        run: |
          docker load --input /tmp/${{ inputs.appName }}.tar
          #docker load --input /tmp/package.tar
          docker image ls -a
          docker push --all-tags ghcr.io/${{ github.repository }}/${{ inputs.appName }}
          #docker push --all-tags ghcr.io/vivek-twi/sifchain-ui
#      - name: 'Setup yq'
#        uses: dcarbone/install-yq-action@v1.1.1
#      - name: Update Image Tag for dev env
#        run: scripts/update_image_tag.sh ${{ inputs.appName }}:${{ github.sha }}
