name: Build Docker Image
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      appName:
        description: 'Name of the Application - for which CI is triggered'
        required: true
        type: string
      branch:
        description: 'Name of the branch - to checkout code. By default, checkout will be from main branch'
        required: false
        type: string
        default: 'master'

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ inputs.appName }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            #type=sha
            #type=semver,pattern={{version}}
            #type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/${{ inputs.appName }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.appName }}
          path: /tmp/${{ inputs.appName }}.tar
