name: Build, Scan and Publish Docker Image
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      appName:
        description: 'Name of the Application - for which CI is triggered'
        required: true
        type: string
      branch:
        description: 'Name of the branch - to checkout code. By default, checkout will be from main branch'
        required: false
        type: string
        default: 'main'

jobs:
  docker-build:
    name: Build Docker Image
    uses: ./.github/workflows/docker-build.yaml
    with:
      appName: ${{ inputs.appName }}

  container-scan:
    name: Scan Docker Image
    uses: ./.github/workflows/security-container-scan.yaml
    needs: [ docker-build ]
    with:
      image-name: ghcr.io/${{ github.repository }}/${{ inputs.appName }}:latest
      appName: ${{ inputs.appName }}

  docker-push:
    name: Push Docker Image to Registry
    uses: ./.github/workflows/docker-push.yaml
    needs: [ docker-build, container-scan ]
    with:
      appName: ${{ inputs.appName }}
